### ISSUE TITLE
Bitcode regression in SpeechKit 2.1.6

### ISSUE THREAD

**Issue by martinc** [NuanceDev/speechkit-ios#2]
A project including SpeechKit 2.1.6 will not build with Bitcode enabled. SpeechKit 2.1.5 will build with bitcode.

To reproduce:

Create a new Xcode project

run pod init (With Cocoapods version 1.0.1)

add SpeechKit 1.2.6 to Podfile

run pod install

open the xcode workspace

switch to generic device

run Archive

It will fail with the following Bitcode error:

ld: bitcode bundle could not be generated because '/Users/username/Documents/speechBitcodeTest/Pods/SpeechKit/SpeechKit.framework/SpeechKit(Pods-SpeechKit-dummy.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Now switch the pod to 2.1.5, repeat the build, and it will succeed

**Comment by jkgneu12** [comment]
Thanks @martinc . Looking into this now.

**Comment by jkgneu12** [comment]
This is fixed in 2.1.7. @martinc can you please verify that 2.1.7 fixes your issue? Thanks.

**Comment by martinc** [comment]
Yes @jkgneu12 just built it successfully. Thank you!

**Comment by martinc** [comment]
@jkgneu12 By the way I'm getting a large file size warning on github. Not sure if there is an easy way to fix this.

remote: warning: File Pods/SpeechKit/SpeechKit.framework/SpeechKit is 82.28 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

**Comment by jkgneu12** [comment]
@martinc Unfortunately our SDK is large. It is something we are working on trying to resolve, but I don't see that happening in the near future. Thanks for the heads up.
